# =============================================================================
# WXM多模态预测模型配置文件
# 该配置文件定义了模型训练和预测的所有关键参数
# =============================================================================

# =============================================================================
# 系统环境配置 (System Environment Configuration)（不用调）
# =============================================================================
random_seed: 2024          # 随机种子，确保实验可重复性
gpu_num: 0                 # GPU设备编号，0表示第一个GPU，-1表示使用CPU
log_dir: "log"             # 日志文件保存目录

# =============================================================================
# 数据路径配置 (Data Path Configuration)（不用调）
# =============================================================================
data:
  original_data_path: "data/activity_order_independent_id"    # 原始活动订单数据路径
  historical_activities_path: "data"                          # 历史活动数据路径
  activities_attributes_path: "data"                          # 活动属性数据路径
  dataset_df_path: "data/dataset_df.csv"                      # 处理后的数据集文件路径

# =============================================================================
# 预测目标配置 (Prediction Target Configuration)（可随意调节）
# =============================================================================
prediction:
  freq: "d"                                                   # 数据频率：h(小时), d(天), w(周), m(月)
  target: "uc"                                                # 预测目标：oc(订单量), uc(用户量)
  static_target: "user_sum"                                   # 静态预测目标：oc_sum(订单总数), user_sum(用户总数)

# =============================================================================
# 模型架构配置 (Model Architecture Configuration)（可随意调节）
# =============================================================================
model:
  model_type: "WXM"                    # 模型类型：WXM(多模态融合模型)
  embedding_dim: 32                     # 特征嵌入维度，用于文本和标签特征编码（需要注意为4的整数倍）
  d_model: 128                          # 模型主隐藏层维度，Transformer架构的核心维度（需要注意为4的整数倍）
  d_s: 64                               # 静态预测分支隐藏层维度，用于处理活动属性特征（需要注意为4的整数倍）
  d_n: 64                               # 动态预测分支隐藏层维度，用于处理时间序列特征（需要注意为4的整数倍）
  num_attn_heads: 1                     # 多头注意力机制中的头数，影响特征交互能力（最好不要超过8）
  num_hidden_layers: 2                  # Transformer编码器的隐藏层数量（最好不要超过6层）
  dropout: 0.4                          # Dropout比率，防止过拟合（最好不要超过0.5）
  use_encoder_mask: 1                   # 是否使用编码器掩码，1启用，0禁用
  autoregressive: 0                     # 是否使用自回归模式，0禁用，1启用（如果为1，则需要将use_encoder_mask设置为0）

# =============================================================================
# 特征工程配置 (Feature Engineering Configuration)（可随意调节）
# =============================================================================
features:
  use_img: false                        # 是否使用图像特征，false表示不使用
  use_text_attributes: true             # 是否使用文本属性特征（活动名称、标题、产品名称）
  use_label_attributes: true            # 是否使用标签属性特征（客户ID、模板ID、活动类型等）
  use_numeric_attributes: true          # 是否使用数值属性特征（预算、奖励数量、持续时间）
  use_temporal_features: true           # 是否使用时间特征（日、周、月、年）
  use_current_seq: true                 # 是否使用当前序列特征
  use_similar: false                    # 是否使用相似序列特征

# =============================================================================
# 训练超参数配置 (Training Hyperparameters Configuration)（可随意调节）
# =============================================================================
training:
  batch_size: 8                         # 训练批次大小，影响内存使用和训练稳定性（显卡内存大可以调大，否则调小，需要为4的整数倍）
  use_lr_scheduler: true                # 是否使用学习率调度器，动态调整学习率
  loss: "mae"                           # 损失函数类型：mae(平均绝对误差), mse(均方误差), mape(平均绝对百分比误差)

# =============================================================================
# 静态预测训练配置 (Static Prediction Training Configuration)（可随意调节）
# =============================================================================
static_training:
  static_epochs: 100                     # 静态预测模型训练轮数
  static_learning_rate: 0.1             # 静态预测模型学习率（不要太大<=0.1，否则容易过拟合）
  static_output_type: "value"           # 静态预测输出类型：value(单点预测), quantile(分位数预测)
  num_gated_blocks: 2                   # 门控残差块数量，用于特征权重分配和梯度优化

# =============================================================================
# 动态预测训练配置 (Dynamic Prediction Training Configuration)（可随意调节）
# =============================================================================
dynamic_training:
  dynamic_epochs: 100                   # 动态预测模型训练轮数
  dynamic_learning_rate: 0.1            # 动态预测模型学习率（不要太大<=0.1，否则容易过拟合）

# =============================================================================
# 序列处理配置 (Sequence Processing Configuration)（仅可调节前俩项参数）
# =============================================================================
sequence:
  current_seq_len: 14                   # 当前序列长度，输入的历史数据天数
  predict_seq_len: 7                    # 预测序列长度，输出的预测数据天数
  total_seq_len: 30                     # 总序列长度，包括历史、当前和预测的总天数
  sequence_process_type: "LTTB"         # 序列处理类型：LTTB(下采样), autoencoder(自编码器)
  apply_diff: true                      # 是否对序列数据应用差分处理，减少趋势影响
  apply_smoothing: true                 # 是否对序列数据应用平滑处理，减少噪声影响
  series_scale: false                   # 是否对序列数据进行缩放，false表示不缩放
  feature_scale: true                   # 是否对特征数据进行缩放，true表示启用特征标准化

# =============================================================================
# DDN归一化配置 (DDN Normalization Configuration)（不用调）
# DDN: Denoising Diffusion Normalization，去噪扩散归一化
# =============================================================================
ddn:
  use_ddn_normalization: true           # 是否启用DDN归一化，自适应时间序列归一化
  j: 0                                  # 小波分解层数，0表示不进行小波分解
  learnable: false                      # 是否使用可学习的DDN参数，false表示使用固定参数
  wavelet: "coif3"                      # 小波基函数类型：coif3(Coiflet小波)，用于信号分解
  dr: 0.01                              # 扩散率，控制归一化过程的强度
  pre_epoch: 5                          # 预训练轮数，DDN模型预训练阶段
  twice_epoch: 1                        # 二次训练轮数，DDN模型微调阶段
  use_norm: "sliding"                   # 归一化方式：sliding(滑动窗口), global(全局)
  kernel_len: 7                         # 卷积核长度，用于时间序列特征提取
  hkernel_len: 5                        # 水平卷积核长度，用于空间特征提取
  station_lr: 0.0001                    # 平稳化学习率，用于DDN参数优化
  station_type: "adaptive"              # 平稳化类型：adaptive(自适应), fixed(固定)
  pd_ff: 1024                           # 前馈网络隐藏层维度，用于DDN特征变换
  pd_model: 512                         # DDN模型隐藏层维度
  pe_layers: 2                          # 位置编码层数，用于序列位置信息编码 